import type { ProductType, Sex } from "./types";

export type Trigger =
  | { kind: "biomarker_status"; key: string; statuses: Array<"low" | "high" | "suboptimal" | "critical"> }
  | { kind: "goal"; value: string }
  | { kind: "symptom"; value: string }
  | { kind: "condition"; value: string }
  | { kind: "medication"; value: string }
  | { kind: "allergy"; value: string }
  | { kind: "pregnancy"; value: "pregnant" | "breastfeeding" | "trying" | "none" }
  | { kind: "diet"; value: string }
  | { kind: "lifestyle_score"; field: LifestyleScoreField; op: "<=" | ">=" | "=="; value: number }
  | { kind: "lifestyle_category"; field: LifestyleCategoryField; values: string[] }
  | { kind: "lifestyle_multi"; field: "sport_type" | "symptoms"; values: string[] };

export type LifestyleScoreField =
  | "sleep_quality"
  | "morning_energy"
  | "stress_level"
  | "energy_low";

export type LifestyleCategoryField =
  | "diet"
  | "meals_per_day"
  | "fish_per_week"
  | "processed_food"
  | "veg_fruit"
  | "water"
  | "coffee"
  | "alcohol"
  | "smoking"
  | "sleep_hours"
  | "night_wake"
  | "sport_frequency"
  | "sitting_hours"
  | "outdoor_time";

export type Product = {
  id: string;
  sku: string;
  product_type: ProductType;
  name: string;
  dosage: string;
  timing: "morgens" | "mittags" | "abends" | "mit Mahlzeit" | "2x täglich";
  pill_color: string;
  pill_shape: "capsule" | "round" | "oval";
  category: string;
  short_benefit: string;
  price_single: number;
  price_subscription: number;
  sex?: Sex[];
  min_age?: number;
  triggers: Trigger[];
  contraindications: string[];
  interactions: Array<{ when: string; note: string }>;
  base_score: number;
};

// Subscription discount for module monthly rations (approx. −15% rounded down).
const subPrice = (single: number): number => Math.round((single * 0.85) * 10) / 10;

export const PRODUCTS: Product[] = [
  {
    id: "vitamin_d3_k2",
    sku: "MOD-VD-30D",
    product_type: "module",
    name: "Vitamin D3 + K2",
    dosage: "5000 IE D3 + 100 µg K2",
    timing: "mit Mahlzeit",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Vitamine",
    short_benefit: "Knochen, Immunsystem, Hormonbalance",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "biomarker_status", key: "vitamin_d", statuses: ["low", "suboptimal", "critical"] },
      { kind: "biomarker_status", key: "testosterone", statuses: ["low", "suboptimal"] },
      { kind: "goal", value: "Immunsystem" },
      { kind: "goal", value: "Longevity" },
      { kind: "condition", value: "Osteoporose" },
      { kind: "condition", value: "Osteopenie" },
      { kind: "lifestyle_category", field: "outdoor_time", values: ["Selten", "Fast nie"] },
    ],
    contraindications: ["blood_thinner_strict"],
    interactions: [
      { when: "blood_thinner", note: "Bei Marcumar/Warfarin ärztliche Absprache wegen Vitamin K2." },
    ],
    base_score: 9,
  },
  {
    id: "magnesium_glycinate",
    sku: "MOD-MAG-30D",
    product_type: "module",
    name: "Magnesium-Bisglycinat",
    dosage: "200 mg elementar",
    timing: "abends",
    pill_color: "#2F3E32",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Schlaf, Muskelentspannung, Nervensystem",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    triggers: [
      { kind: "biomarker_status", key: "magnesium", statuses: ["low", "suboptimal"] },
      { kind: "goal", value: "Schlaf" },
      { kind: "goal", value: "Stressabbau" },
      { kind: "lifestyle_score", field: "sleep_quality", op: "<=", value: 2 },
      { kind: "lifestyle_score", field: "stress_level", op: ">=", value: 4 },
      { kind: "symptom", value: "Muskelkrämpfe" },
      { kind: "symptom", value: "Kopfschmerzen" },
      { kind: "condition", value: "Peri-/Menopause" },
      { kind: "lifestyle_multi", field: "sport_type", values: ["Kraftsport", "HIIT", "Ausdauer"] },
    ],
    contraindications: ["kidney_disease_severe"],
    interactions: [],
    base_score: 8,
  },
  {
    id: "omega3_fish",
    sku: "MOD-OM3-30D",
    product_type: "module",
    name: "Omega-3 (EPA/DHA)",
    dosage: "2 g EPA/DHA",
    timing: "mit Mahlzeit",
    pill_color: "#D4736B",
    pill_shape: "capsule",
    category: "Fettsäuren",
    short_benefit: "Herz-Kreislauf, Entzündung, Gehirn",
    price_single: 11.9,
    price_subscription: subPrice(11.9),
    triggers: [
      { kind: "biomarker_status", key: "omega_3_index", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "crp_hs", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "triglycerides", statuses: ["high", "suboptimal"] },
      { kind: "lifestyle_category", field: "fish_per_week", values: ["Nie", "1×"] },
      { kind: "diet", value: "Vegan" },
      { kind: "diet", value: "Vegetarisch" },
      { kind: "goal", value: "Longevity" },
      { kind: "symptom", value: "Gelenkschmerzen" },
    ],
    contraindications: ["high_dose_blood_thinner"],
    interactions: [
      { when: "blood_thinner", note: "Bei Blutverdünnern Dosis mit Arzt abstimmen." },
    ],
    base_score: 9,
  },
  {
    id: "b_complex_active",
    sku: "MOD-BCO-30D",
    product_type: "module",
    name: "B-Komplex aktiv (methyliert)",
    dosage: "1 Kapsel",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Vitamine",
    short_benefit: "Energiestoffwechsel, Homocystein, Nerven",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "biomarker_status", key: "homocysteine", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "vitamin_b12", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "folate", statuses: ["low", "suboptimal"] },
      { kind: "diet", value: "Vegan" },
      { kind: "diet", value: "Vegetarisch" },
      { kind: "lifestyle_category", field: "alcohol", values: ["Täglich", "Fast täglich"] },
      { kind: "symptom", value: "Müdigkeit" },
      { kind: "symptom", value: "Konzentrationsprobleme" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 8,
  },
  {
    id: "vitamin_b12_methyl",
    sku: "MOD-B12-30D",
    product_type: "module",
    name: "Vitamin B12 (Methylcobalamin)",
    dosage: "500 µg",
    timing: "morgens",
    pill_color: "#D4736B",
    pill_shape: "round",
    category: "Vitamine",
    short_benefit: "Energie, Nervensystem, Hämatopoese",
    price_single: 3.5,
    price_subscription: subPrice(3.5),
    triggers: [
      { kind: "biomarker_status", key: "vitamin_b12", statuses: ["low", "suboptimal", "critical"] },
      { kind: "biomarker_status", key: "homocysteine", statuses: ["high", "suboptimal"] },
      { kind: "diet", value: "Vegan" },
      { kind: "medication", value: "Protonenpumpenhemmer (Omeprazol, Pantoprazol)" },
      { kind: "medication", value: "Insulin / Metformin" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 8,
  },
  {
    id: "vitamin_b6",
    sku: "MOD-B6-30D",
    product_type: "module",
    name: "Vitamin B6 (P5P)",
    dosage: "25 mg",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "round",
    category: "Vitamine",
    short_benefit: "Hormonbalance, Nervensystem, PMS-Unterstützung",
    price_single: 3.9,
    price_subscription: subPrice(3.9),
    sex: ["female"],
    triggers: [
      { kind: "biomarker_status", key: "homocysteine", statuses: ["high", "suboptimal"] },
      { kind: "goal", value: "Hormonbalance" },
      { kind: "symptom", value: "Stimmungsschwankungen" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 6,
  },
  {
    id: "glycine",
    sku: "MOD-GLY-30D",
    product_type: "module",
    name: "Glycin",
    dosage: "3 g",
    timing: "abends",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Aminosäuren",
    short_benefit: "Schlafqualität, GABA-Modulation",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "goal", value: "Schlaf" },
      { kind: "lifestyle_score", field: "sleep_quality", op: "<=", value: 2 },
      { kind: "symptom", value: "Stimmungsschwankungen" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "zinc_picolinate",
    sku: "MOD-ZIN-30D",
    product_type: "module",
    name: "Zink-Bisglycinat",
    dosage: "15 mg",
    timing: "abends",
    pill_color: "#94A3A0",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Immunsystem, Haut, Hormone",
    price_single: 3.5,
    price_subscription: subPrice(3.5),
    triggers: [
      { kind: "biomarker_status", key: "zinc", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "tsh", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "testosterone", statuses: ["low", "suboptimal"] },
      { kind: "goal", value: "Immunsystem" },
      { kind: "goal", value: "Hautbild" },
      { kind: "symptom", value: "Haarausfall" },
      { kind: "symptom", value: "Hautprobleme" },
      { kind: "symptom", value: "Infektanfälligkeit" },
      { kind: "diet", value: "Vegan" },
    ],
    contraindications: [],
    interactions: [
      { when: "thyroid_medication", note: "Einnahme zeitlich zu L-Thyroxin versetzen (mind. 4 h)." },
    ],
    base_score: 7,
  },
  {
    id: "selenium",
    sku: "MOD-SEL-30D",
    product_type: "module",
    name: "Selen",
    dosage: "200 µg",
    timing: "morgens",
    pill_color: "#94A3A0",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Schilddrüse, Antioxidation, Haare",
    price_single: 3.5,
    price_subscription: subPrice(3.5),
    triggers: [
      { kind: "biomarker_status", key: "selenium", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "tsh", statuses: ["high", "suboptimal"] },
      { kind: "symptom", value: "Haarausfall" },
      { kind: "condition", value: "Schilddrüsenunterfunktion (Hashimoto)" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 6,
  },
  {
    id: "vitamin_c",
    sku: "MOD-VC-30D",
    product_type: "module",
    name: "Vitamin C (gepuffert)",
    dosage: "500 mg",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Vitamine",
    short_benefit: "Antioxidativ, Immunsystem, Eisenaufnahme",
    price_single: 3.9,
    price_subscription: subPrice(3.9),
    triggers: [
      { kind: "biomarker_status", key: "ferritin", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "iron", statuses: ["low", "suboptimal"] },
      { kind: "goal", value: "Immunsystem" },
      { kind: "goal", value: "Hautbild" },
      { kind: "lifestyle_category", field: "smoking", values: ["Täglich", "Gelegentlich", "Vapen/E-Zigarette"] },
      { kind: "lifestyle_category", field: "veg_fruit", values: ["0–1", "2–3"] },
    ],
    contraindications: ["hemochromatosis"],
    interactions: [],
    base_score: 6,
  },
  {
    id: "probiotics",
    sku: "MOD-PRO-30D",
    product_type: "module",
    name: "Probiotika Blend",
    dosage: "10 Mrd. KBE, 10 Stämme",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Darmgesundheit",
    short_benefit: "Mikrobiom, Verdauung, Immunsystem",
    price_single: 9.9,
    price_subscription: subPrice(9.9),
    triggers: [
      { kind: "goal", value: "Verdauung" },
      { kind: "goal", value: "Immunsystem" },
      { kind: "symptom", value: "Verdauungsbeschwerden" },
      { kind: "condition", value: "Reizdarm" },
      { kind: "condition", value: "Reflux" },
      { kind: "medication", value: "Protonenpumpenhemmer (Omeprazol, Pantoprazol)" },
    ],
    contraindications: ["immunosuppressed"],
    interactions: [],
    base_score: 7,
  },
  {
    id: "inulin",
    sku: "MOD-INU-30D",
    product_type: "module",
    name: "Inulin (Präbiotikum)",
    dosage: "5 g",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Darmgesundheit",
    short_benefit: "Präbiotische Ballaststoffe, Darmflora",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "goal", value: "Verdauung" },
      { kind: "symptom", value: "Verdauungsbeschwerden" },
      { kind: "condition", value: "Reizdarm" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "collagen",
    sku: "MOD-COL-30D",
    product_type: "module",
    name: "Marine Collagen",
    dosage: "5 g",
    timing: "morgens",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Bindegewebe",
    short_benefit: "Haut, Gelenke, Bindegewebe",
    price_single: 12.9,
    price_subscription: subPrice(12.9),
    triggers: [
      { kind: "goal", value: "Hautbild" },
      { kind: "symptom", value: "Brüchige Nägel" },
      { kind: "symptom", value: "Hautprobleme" },
      { kind: "symptom", value: "Gelenkschmerzen" },
      { kind: "condition", value: "Arthrose" },
    ],
    contraindications: ["fish_allergy"],
    interactions: [],
    base_score: 6,
  },
  {
    id: "hyaluronic_acid",
    sku: "MOD-HYA-30D",
    product_type: "module",
    name: "Hyaluronsäure",
    dosage: "120 mg",
    timing: "mit Mahlzeit",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Bindegewebe",
    short_benefit: "Hautfeuchtigkeit, Gelenke",
    price_single: 7.9,
    price_subscription: subPrice(7.9),
    triggers: [
      { kind: "goal", value: "Hautbild" },
      { kind: "symptom", value: "Hautprobleme" },
      { kind: "symptom", value: "Gelenkschmerzen" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "silica",
    sku: "MOD-SIL-30D",
    product_type: "module",
    name: "Silica (Kieselsäure)",
    dosage: "100 mg",
    timing: "morgens",
    pill_color: "#94A3A0",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Haare, Nägel, Bindegewebe",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "symptom", value: "Haarausfall" },
      { kind: "symptom", value: "Brüchige Nägel" },
      { kind: "goal", value: "Hautbild" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "astaxanthin",
    sku: "MOD-AST-30D",
    product_type: "module",
    name: "Astaxanthin",
    dosage: "12 mg",
    timing: "mit Mahlzeit",
    pill_color: "#D4736B",
    pill_shape: "capsule",
    category: "Antioxidantien",
    short_benefit: "Zellschutz, Haut, UV-Resilienz",
    price_single: 8.9,
    price_subscription: subPrice(8.9),
    triggers: [
      { kind: "goal", value: "Hautbild" },
      { kind: "goal", value: "Longevity" },
      { kind: "symptom", value: "Hautprobleme" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "biotin",
    sku: "MOD-BIO-30D",
    product_type: "module",
    name: "Biotin",
    dosage: "5 mg",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "round",
    category: "Vitamine",
    short_benefit: "Haare, Nägel, Haut",
    price_single: 2.9,
    price_subscription: subPrice(2.9),
    triggers: [
      { kind: "symptom", value: "Haarausfall" },
      { kind: "symptom", value: "Brüchige Nägel" },
      { kind: "goal", value: "Hautbild" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "l_cysteine",
    sku: "MOD-CYS-30D",
    product_type: "module",
    name: "L-Cystein",
    dosage: "500 mg",
    timing: "morgens",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Aminosäuren",
    short_benefit: "Haare, Leber-Detox (Glutathion)",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    triggers: [
      { kind: "symptom", value: "Haarausfall" },
      { kind: "goal", value: "Hautbild" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "msm",
    sku: "MOD-MSM-30D",
    product_type: "module",
    name: "MSM",
    dosage: "1000 mg",
    timing: "mit Mahlzeit",
    pill_color: "#94A3A0",
    pill_shape: "capsule",
    category: "Gelenke",
    short_benefit: "Gelenke, Haut, Entzündungsmodulation",
    price_single: 4.5,
    price_subscription: subPrice(4.5),
    triggers: [
      { kind: "symptom", value: "Gelenkschmerzen" },
      { kind: "condition", value: "Arthrose" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "ashwagandha",
    sku: "MOD-ASH-30D",
    product_type: "module",
    name: "Ashwagandha (KSM-66)",
    dosage: "300 mg",
    timing: "abends",
    pill_color: "#2F3E32",
    pill_shape: "capsule",
    category: "Adaptogene",
    short_benefit: "Stressadaptation, Schlaf, Regeneration",
    price_single: 6.9,
    price_subscription: subPrice(6.9),
    triggers: [
      { kind: "goal", value: "Stressabbau" },
      { kind: "goal", value: "Schlaf" },
      { kind: "lifestyle_score", field: "stress_level", op: ">=", value: 4 },
      { kind: "lifestyle_score", field: "sleep_quality", op: "<=", value: 2 },
      { kind: "symptom", value: "Stimmungsschwankungen" },
      { kind: "biomarker_status", key: "testosterone", statuses: ["low", "suboptimal"] },
      { kind: "condition", value: "Peri-/Menopause" },
    ],
    contraindications: ["pregnancy", "thyroid_hyper", "autoimmune_active"],
    interactions: [
      { when: "thyroid_medication", note: "Kann Schilddrüsenaktivität erhöhen — bei Hashimoto/L-Thyroxin Rücksprache." },
    ],
    base_score: 6,
  },
  {
    id: "rhodiola",
    sku: "MOD-RHO-30D",
    product_type: "module",
    name: "Rhodiola Rosea",
    dosage: "200 mg",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Adaptogene",
    short_benefit: "Stressresistenz, mentale Energie",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    triggers: [
      { kind: "goal", value: "Stressabbau" },
      { kind: "goal", value: "Energie" },
      { kind: "goal", value: "Fokus" },
      { kind: "symptom", value: "Müdigkeit" },
      { kind: "lifestyle_score", field: "energy_low", op: ">=", value: 4 },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 5,
  },
  {
    id: "l_theanine",
    sku: "MOD-THE-30D",
    product_type: "module",
    name: "L-Theanin",
    dosage: "200 mg",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Aminosäuren",
    short_benefit: "Ruhiger Fokus, Stressresistenz",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "goal", value: "Stressabbau" },
      { kind: "goal", value: "Fokus" },
      { kind: "symptom", value: "Konzentrationsprobleme" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "coq10",
    sku: "MOD-COQ-30D",
    product_type: "module",
    name: "CoQ10 (Ubiquinol)",
    dosage: "100 mg",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Mitochondrial",
    short_benefit: "Zellenergie, Herz, Kognition",
    price_single: 7.9,
    price_subscription: subPrice(7.9),
    triggers: [
      { kind: "medication", value: "Cholesterinsenker (Statine)" },
      { kind: "goal", value: "Energie" },
      { kind: "goal", value: "Longevity" },
      { kind: "symptom", value: "Müdigkeit" },
      { kind: "lifestyle_score", field: "energy_low", op: ">=", value: 4 },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
    min_age: 35,
  },
  {
    id: "iron_bisglycinate",
    sku: "MOD-FER-30D",
    product_type: "module",
    name: "Eisen-Bisglycinat",
    dosage: "20 mg",
    timing: "morgens",
    pill_color: "#D4736B",
    pill_shape: "capsule",
    category: "Mineralstoffe",
    short_benefit: "Sauerstofftransport, Energie",
    price_single: 4.9,
    price_subscription: subPrice(4.9),
    triggers: [
      { kind: "biomarker_status", key: "ferritin", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "iron", statuses: ["low", "suboptimal"] },
      { kind: "biomarker_status", key: "hemoglobin", statuses: ["low"] },
      { kind: "symptom", value: "Müdigkeit" },
      { kind: "symptom", value: "Haarausfall" },
      { kind: "diet", value: "Vegan" },
      { kind: "diet", value: "Vegetarisch" },
    ],
    contraindications: ["hemochromatosis"],
    interactions: [],
    base_score: 7,
  },
  {
    id: "folate_mthf",
    sku: "MOD-FOL-30D",
    product_type: "module",
    name: "Folat (5-MTHF)",
    dosage: "400 µg",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "round",
    category: "Vitamine",
    short_benefit: "Zellteilung, Homocystein, Kinderwunsch",
    price_single: 3.9,
    price_subscription: subPrice(3.9),
    triggers: [
      { kind: "biomarker_status", key: "folate", statuses: ["low", "suboptimal"] },
      { kind: "pregnancy", value: "trying" },
      { kind: "pregnancy", value: "pregnant" },
      { kind: "biomarker_status", key: "homocysteine", statuses: ["high", "suboptimal"] },
    ],
    sex: ["female"],
    contraindications: [],
    interactions: [],
    base_score: 7,
  },
  {
    id: "vitex",
    sku: "MOD-VIT-30D",
    product_type: "module",
    name: "Vitex Agnus Castus",
    dosage: "400 mg",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "round",
    category: "Pflanzlich",
    short_benefit: "Zyklus-Regulation",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    triggers: [
      { kind: "symptom", value: "Stimmungsschwankungen" },
      { kind: "goal", value: "Hormonbalance" },
      { kind: "condition", value: "PCOS" },
    ],
    sex: ["female"],
    contraindications: ["pregnancy", "hormonal_contraception"],
    interactions: [
      { when: "hormonal_contraception", note: "Kann mit hormoneller Verhütung interferieren — bitte Rücksprache." },
    ],
    base_score: 4,
  },
  {
    id: "inositol",
    sku: "MOD-INO-30D",
    product_type: "module",
    name: "Myo-Inositol",
    dosage: "2 g",
    timing: "2x täglich",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Pflanzlich",
    short_benefit: "Insulinsensitivität, PCOS-Unterstützung",
    price_single: 6.9,
    price_subscription: subPrice(6.9),
    triggers: [
      { kind: "condition", value: "PCOS" },
      { kind: "biomarker_status", key: "insulin_fasting", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "hba1c", statuses: ["high", "suboptimal"] },
      { kind: "goal", value: "Hormonbalance" },
    ],
    sex: ["female"],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "d_chiro_inositol",
    sku: "MOD-DCI-30D",
    product_type: "module",
    name: "D-Chiro-Inositol",
    dosage: "600 mg",
    timing: "2x täglich",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Pflanzlich",
    short_benefit: "PCOS-Stack, Ovar-Funktion",
    price_single: 9.9,
    price_subscription: subPrice(9.9),
    sex: ["female"],
    triggers: [
      { kind: "condition", value: "PCOS" },
      { kind: "biomarker_status", key: "hba1c", statuses: ["high", "suboptimal"] },
      { kind: "pregnancy", value: "trying" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "chromium",
    sku: "MOD-CHR-30D",
    product_type: "module",
    name: "Chrom Picolinat",
    dosage: "200 µg",
    timing: "mit Mahlzeit",
    pill_color: "#94A3A0",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Blutzucker, Heißhunger",
    price_single: 3.5,
    price_subscription: subPrice(3.5),
    triggers: [
      { kind: "biomarker_status", key: "hba1c", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "insulin_fasting", statuses: ["high", "suboptimal"] },
      { kind: "goal", value: "Abnehmen" },
      { kind: "condition", value: "Prädiabetes" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "berberine",
    sku: "MOD-BER-30D",
    product_type: "module",
    name: "Berberine HCL",
    dosage: "500 mg",
    timing: "2x täglich",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Pflanzlich",
    short_benefit: "Metabolische Kontrolle, Blutzucker",
    price_single: 8.9,
    price_subscription: subPrice(8.9),
    triggers: [
      { kind: "biomarker_status", key: "hba1c", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "insulin_fasting", statuses: ["high", "suboptimal"] },
      { kind: "biomarker_status", key: "triglycerides", statuses: ["high", "suboptimal"] },
      { kind: "goal", value: "Abnehmen" },
      { kind: "condition", value: "Prädiabetes" },
      { kind: "condition", value: "Diabetes Typ 2" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 6,
  },
  {
    id: "alpha_lipoic_acid",
    sku: "MOD-ALA-30D",
    product_type: "module",
    name: "Alpha-Liponsäure",
    dosage: "300 mg",
    timing: "mit Mahlzeit",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Antioxidantien",
    short_benefit: "Insulinsensitivität, Zellschutz",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    triggers: [
      { kind: "biomarker_status", key: "hba1c", statuses: ["high", "suboptimal"] },
      { kind: "condition", value: "Diabetes Typ 2" },
      { kind: "goal", value: "Abnehmen" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "boron",
    sku: "MOD-BOR-30D",
    product_type: "module",
    name: "Bor",
    dosage: "3 mg",
    timing: "morgens",
    pill_color: "#94A3A0",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Knochenstoffwechsel, Testosteron-Regulation",
    price_single: 3.5,
    price_subscription: subPrice(3.5),
    triggers: [
      { kind: "biomarker_status", key: "testosterone", statuses: ["low", "suboptimal"] },
      { kind: "condition", value: "Osteopenie" },
      { kind: "condition", value: "Osteoporose" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "calcium_citrate",
    sku: "MOD-CAL-30D",
    product_type: "module",
    name: "Calcium (Citrat)",
    dosage: "500 mg",
    timing: "abends",
    pill_color: "#EDE8DF",
    pill_shape: "round",
    category: "Mineralstoffe",
    short_benefit: "Knochendichte, Muskelkontraktion",
    price_single: 5.5,
    price_subscription: subPrice(5.5),
    min_age: 40,
    triggers: [
      { kind: "condition", value: "Osteoporose" },
      { kind: "condition", value: "Osteopenie" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "lions_mane",
    sku: "MOD-LIM-30D",
    product_type: "module",
    name: "Lion's Mane Extrakt",
    dosage: "500 mg",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Brain",
    short_benefit: "Fokus, Nerven-Wachstumsfaktor",
    price_single: 7.9,
    price_subscription: subPrice(7.9),
    triggers: [
      { kind: "goal", value: "Fokus" },
      { kind: "symptom", value: "Konzentrationsprobleme" },
      { kind: "symptom", value: "Gedächtnisprobleme" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "bacopa",
    sku: "MOD-BAC-30D",
    product_type: "module",
    name: "Bacopa Monnieri",
    dosage: "300 mg",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Brain",
    short_benefit: "Gedächtnis, Lernfähigkeit",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    triggers: [
      { kind: "goal", value: "Fokus" },
      { kind: "symptom", value: "Gedächtnisprobleme" },
      { kind: "symptom", value: "Konzentrationsprobleme" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  {
    id: "cdp_choline",
    sku: "MOD-CDP-30D",
    product_type: "module",
    name: "CDP-Choline (Citicolin)",
    dosage: "500 mg",
    timing: "morgens",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Brain",
    short_benefit: "Fokus, Neuroprotektion",
    price_single: 9.9,
    price_subscription: subPrice(9.9),
    triggers: [
      { kind: "goal", value: "Fokus" },
      { kind: "symptom", value: "Konzentrationsprobleme" },
      { kind: "symptom", value: "Gedächtnisprobleme" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 5,
  },
  {
    id: "black_cohosh",
    sku: "MOD-BLC-30D",
    product_type: "module",
    name: "Traubensilberkerze (Black Cohosh)",
    dosage: "40 mg Extrakt",
    timing: "morgens",
    pill_color: "#2F3E32",
    pill_shape: "capsule",
    category: "Menopause",
    short_benefit: "Hitzewallungen, Schlafqualität in Wechseljahren",
    price_single: 6.9,
    price_subscription: subPrice(6.9),
    sex: ["female"],
    min_age: 40,
    triggers: [
      { kind: "condition", value: "Peri-/Menopause" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 5,
  },
  {
    id: "sage_extract",
    sku: "MOD-SAG-30D",
    product_type: "module",
    name: "Salbei-Extrakt",
    dosage: "300 mg",
    timing: "morgens",
    pill_color: "#8FA68E",
    pill_shape: "capsule",
    category: "Menopause",
    short_benefit: "Hitzewallungen, Schweißregulation",
    price_single: 5.9,
    price_subscription: subPrice(5.9),
    sex: ["female"],
    min_age: 40,
    triggers: [
      { kind: "condition", value: "Peri-/Menopause" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 4,
  },
  {
    id: "isoflavones",
    sku: "MOD-ISO-30D",
    product_type: "module",
    name: "Isoflavone (Soja/Rotklee)",
    dosage: "50 mg",
    timing: "mit Mahlzeit",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Menopause",
    short_benefit: "Phytoöstrogene, Wechseljahrsbeschwerden",
    price_single: 6.5,
    price_subscription: subPrice(6.5),
    sex: ["female"],
    min_age: 40,
    triggers: [
      { kind: "condition", value: "Peri-/Menopause" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 4,
  },
  {
    id: "spermidine",
    sku: "MOD-SPE-30D",
    product_type: "module",
    name: "Spermidine",
    dosage: "3 mg",
    timing: "abends",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Longevity",
    short_benefit: "Autophagie, Zellregeneration",
    price_single: 12.9,
    price_subscription: subPrice(12.9),
    min_age: 40,
    triggers: [
      { kind: "goal", value: "Longevity" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 4,
  },
  {
    id: "urolithin_a",
    sku: "MOD-URO-30D",
    product_type: "module",
    name: "Urolithin A",
    dosage: "250 mg",
    timing: "morgens",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Longevity",
    short_benefit: "Mitophagie, Muskelqualität",
    price_single: 16.9,
    price_subscription: subPrice(16.9),
    min_age: 40,
    triggers: [
      { kind: "goal", value: "Longevity" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 4,
  },
  {
    id: "nmn",
    sku: "MOD-NMN-30D",
    product_type: "module",
    name: "NMN",
    dosage: "300 mg",
    timing: "morgens",
    pill_color: "#EDE8DF",
    pill_shape: "capsule",
    category: "Longevity",
    short_benefit: "NAD+-Vorläufer, Zellenergie",
    price_single: 18.9,
    price_subscription: subPrice(18.9),
    min_age: 40,
    triggers: [
      { kind: "goal", value: "Longevity" },
      { kind: "goal", value: "Energie" },
    ],
    contraindications: ["pregnancy"],
    interactions: [],
    base_score: 4,
  },
  {
    id: "pqq",
    sku: "MOD-PQQ-30D",
    product_type: "module",
    name: "PQQ",
    dosage: "20 mg",
    timing: "morgens",
    pill_color: "#C4964A",
    pill_shape: "capsule",
    category: "Longevity",
    short_benefit: "Mitochondrien-Biogenese",
    price_single: 9.9,
    price_subscription: subPrice(9.9),
    min_age: 35,
    triggers: [
      { kind: "goal", value: "Longevity" },
      { kind: "goal", value: "Energie" },
    ],
    contraindications: [],
    interactions: [],
    base_score: 4,
  },
  // TODO: weitere Longevity- / Hormone-Balance-Module aus XLSX (Quercetin, NR,
  // Apigenin separat), sobald Shopify-Varianten angelegt sind.
];

export const PRODUCT_BY_ID: Map<string, Product> = new Map(PRODUCTS.map((p) => [p.id, p]));
export const PRODUCT_BY_SKU: Map<string, Product> = new Map(PRODUCTS.map((p) => [p.sku, p]));

export type CoreBoxIngredient = {
  name: string;
  dosage: string;
  form: string;
  goal: string;
};

export type CoreBoxEpisodeDef = {
  id: "morning" | "midday" | "afternoon" | "night";
  label: string;
  goal: string;
  ingredients: CoreBoxIngredient[];
};

export const CORE_BOX = {
  sku: "COREBOX-30D",
  name: "SUPGREAT Core Box",
  tagline: "22 Wirkstoffe, 4 Tagespacks — das Fundament deines Protokolls.",
  price_single: 89,
  price_subscription: 79,
  ingredient_count: 22,
  episodes: [
    {
      id: "morning",
      label: "Morning · Activation",
      goal: "Energie-Start & Immun-Support",
      ingredients: [
        { name: "Creatine Monohydrate", dosage: "2 g", form: "Tablette", goal: "Zellenergie" },
        { name: "NR / NMN", dosage: "300 mg", form: "Kapsel", goal: "Zellenergie" },
        { name: "Urolithin A", dosage: "250 mg", form: "Kapsel", goal: "Mitochondrien" },
        { name: "CoQ10 (Ubiquinol)", dosage: "100 mg", form: "Kapsel", goal: "Zellenergie" },
        { name: "Rhodiola Rosea", dosage: "200 mg", form: "Kapsel", goal: "Mentale Aktivierung" },
        { name: "Aktiver B-Komplex", dosage: "Standard", form: "Kapsel", goal: "Stoffwechselstart" },
        { name: "Vitamin D3", dosage: "3000 IE", form: "Kapsel", goal: "Immunsystem" },
        { name: "Vitamin K2", dosage: "100 µg", form: "Kapsel", goal: "Knochen & Gefäße" },
      ],
    },
    {
      id: "midday",
      label: "Midday · Focus",
      goal: "Konzentration & Entzündungsmodulation",
      ingredients: [
        { name: "Creatine Monohydrate", dosage: "2 g", form: "Tablette", goal: "Zellenergie" },
        { name: "Lion's Mane Extrakt", dosage: "500 mg", form: "Kapsel", goal: "Fokus" },
        { name: "L-Theanin", dosage: "200 mg", form: "Kapsel", goal: "Stressresistenz" },
        { name: "Curcumin (bioverfügbar)", dosage: "500 mg", form: "Kapsel", goal: "Entzündungshemmung" },
      ],
    },
    {
      id: "afternoon",
      label: "Afternoon · Sustain",
      goal: "Metabolische Balance & Antioxidation",
      ingredients: [
        { name: "Creatine Monohydrate", dosage: "2 g", form: "Tablette", goal: "Zellenergie" },
        { name: "Berberine HCL", dosage: "500 mg", form: "Kapsel", goal: "Metabolische Kontrolle" },
        { name: "Quercetin", dosage: "250–500 mg", form: "Kapsel", goal: "Antioxidans" },
        { name: "PQQ", dosage: "10–20 mg", form: "Kapsel", goal: "Mitochondrien" },
      ],
    },
    {
      id: "night",
      label: "Night · Recovery",
      goal: "Regeneration, Schlaf & Darm",
      ingredients: [
        { name: "Magnesium Bisglycinat", dosage: "200 mg elementar", form: "Kapsel", goal: "Nervensystem" },
        { name: "Ashwagandha KSM-66", dosage: "300 mg", form: "Kapsel", goal: "Regeneration" },
        { name: "Apigenin", dosage: "50 mg", form: "Kapsel", goal: "Schlaf" },
        { name: "Spermidine", dosage: "3 mg", form: "Kapsel", goal: "Longevity" },
        { name: "Probiotic Blend", dosage: "10–20 Mrd CFU", form: "Kapsel", goal: "Darmgesundheit" },
        { name: "MSM", dosage: "1000 mg", form: "Kapsel", goal: "Gelenke/Haut" },
      ],
    },
  ] as CoreBoxEpisodeDef[],
};
